<template>

  <div class="container firstPageContainer">
    <div class="row">
      <div class="license">
        <div class="ob">
          <div class="text">
            <h1>dolor sit amet.</h1>
            <p><span>Lorem ipsum dolor sit amet, consectetur adipisicing elit. A animi consequatur, cum deleniti dolores doloribus, enim esse hic ipsam numquam obcaecati officiis perspiciatis quidem repellendus saepe temporibus tenetur unde, veritatis.</span><span>Adipisci alias deserunt dolor, doloremque, dolores, laudantium maxime minus modi molestias nam nemo neque quis reprehenderit sequi sint? Adipisci aperiam deleniti doloribus ea eligendi ex libero perspiciatis quidem sunt unde?</span><span>Ad architecto at blanditiis culpa cupiditate deleniti eaque enim eum ex excepturi facilis fugiat illo illum incidunt iste iure laboriosam nisi odio porro quaerat quod reiciendis sapiente tenetur ullam, velit.</span><span>Eum fuga ipsa laborum quibusdam unde voluptate voluptatum. Ab dolorem expedita magni modi pariatur quam rem sunt. Ab, animi beatae debitis eos laboriosam minus mollitia provident quam quas quasi quis.</span><span>Deserunt eius fuga, laboriosam laborum rem velit. Doloribus ex explicabo iure necessitatibus obcaecati qui quia soluta. Commodi cumque cupiditate, debitis dolores esse fugit harum pariatur, perspiciatis quos ullam unde ut!</span><span>Accusamus amet asperiores assumenda aut corporis cum debitis deleniti dicta distinctio earum enim esse facere, facilis harum iste molestias nam non officiis omnis quasi quidem, rem reprehenderit sapiente sed velit!</span><span>A aspernatur, delectus deleniti dolor harum illum perferendis quibusdam reiciendis voluptatum? Beatae consectetur cum enim fuga nisi odio similique! Ad aspernatur cumque doloribus dolorum eaque expedita in, nesciunt nulla sapiente!</span><span>Accusantium aliquid aut cumque cupiditate dolores eaque eveniet excepturi facilis harum illo libero natus nesciunt nulla quae quis quos repudiandae, voluptas voluptate! Ab commodi, doloremque dolorum facilis harum nobis porro!</span><span>A, ad asperiores distinctio doloribus itaque maxime neque nulla porro quibusdam quo sunt veritatis voluptates. Culpa cumque deserunt doloremque incidunt molestias quaerat quidem repellendus? Delectus, doloremque, voluptas? Fugit, recusandae suscipit.</span><span>At blanditiis commodi culpa cupiditate dignissimos, dolorum eos exercitationem facere hic id impedit itaque laborum magni minima numquam odit omnis possimus quidem recusandae repellendus sed sint sit totam ullam voluptatibus.</span></p>
            <p><span>Lorem ipsum dolor sit amet, consectetur adipisicing elit. A animi consequatur, cum deleniti dolores doloribus, enim esse hic ipsam numquam obcaecati officiis perspiciatis quidem repellendus saepe temporibus tenetur unde, veritatis.</span><span>Adipisci alias deserunt dolor, doloremque, dolores, laudantium maxime minus modi molestias nam nemo neque quis reprehenderit sequi sint? Adipisci aperiam deleniti doloribus ea eligendi ex libero perspiciatis quidem sunt unde?</span><span>Ad architecto at blanditiis culpa cupiditate deleniti eaque enim eum ex excepturi facilis fugiat illo illum incidunt iste iure laboriosam nisi odio porro quaerat quod reiciendis sapiente tenetur ullam, velit.</span><span>Eum fuga ipsa laborum quibusdam unde voluptate voluptatum. Ab dolorem expedita magni modi pariatur quam rem sunt. Ab, animi beatae debitis eos laboriosam minus mollitia provident quam quas quasi quis.</span><span>Deserunt eius fuga, laboriosam laborum rem velit. Doloribus ex explicabo iure necessitatibus obcaecati qui quia soluta. Commodi cumque cupiditate, debitis dolores esse fugit harum pariatur, perspiciatis quos ullam unde ut!</span><span>Accusamus amet asperiores assumenda aut corporis cum debitis deleniti dicta distinctio earum enim esse facere, facilis harum iste molestias nam non officiis omnis quasi quidem, rem reprehenderit sapiente sed velit!</span><span>A aspernatur, delectus deleniti dolor harum illum perferendis quibusdam reiciendis voluptatum? Beatae consectetur cum enim fuga nisi odio similique! Ad aspernatur cumque doloribus dolorum eaque expedita in, nesciunt nulla sapiente!</span><span>Accusantium aliquid aut cumque cupiditate dolores eaque eveniet excepturi facilis harum illo libero natus nesciunt nulla quae quis quos repudiandae, voluptas voluptate! Ab commodi, doloremque dolorum facilis harum nobis porro!</span><span>A, ad asperiores distinctio doloribus itaque maxime neque nulla porro quibusdam quo sunt veritatis voluptates. Culpa cumque deserunt doloremque incidunt molestias quaerat quidem repellendus? Delectus, doloremque, voluptas? Fugit, recusandae suscipit.</span><span>At blanditiis commodi culpa cupiditate dignissimos, dolorum eos exercitationem facere hic id impedit itaque laborum magni minima numquam odit omnis possimus quidem recusandae repellendus sed sint sit totam ullam voluptatibus.</span></p>
            <p><span>Lorem ipsum dolor sit amet, consectetur adipisicing elit. A animi consequatur, cum deleniti dolores doloribus, enim esse hic ipsam numquam obcaecati officiis perspiciatis quidem repellendus saepe temporibus tenetur unde, veritatis.</span><span>Adipisci alias deserunt dolor, doloremque, dolores, laudantium maxime minus modi molestias nam nemo neque quis reprehenderit sequi sint? Adipisci aperiam deleniti doloribus ea eligendi ex libero perspiciatis quidem sunt unde?</span><span>Ad architecto at blanditiis culpa cupiditate deleniti eaque enim eum ex excepturi facilis fugiat illo illum incidunt iste iure laboriosam nisi odio porro quaerat quod reiciendis sapiente tenetur ullam, velit.</span><span>Eum fuga ipsa laborum quibusdam unde voluptate voluptatum. Ab dolorem expedita magni modi pariatur quam rem sunt. Ab, animi beatae debitis eos laboriosam minus mollitia provident quam quas quasi quis.</span><span>Deserunt eius fuga, laboriosam laborum rem velit. Doloribus ex explicabo iure necessitatibus obcaecati qui quia soluta. Commodi cumque cupiditate, debitis dolores esse fugit harum pariatur, perspiciatis quos ullam unde ut!</span><span>Accusamus amet asperiores assumenda aut corporis cum debitis deleniti dicta distinctio earum enim esse facere, facilis harum iste molestias nam non officiis omnis quasi quidem, rem reprehenderit sapiente sed velit!</span><span>A aspernatur, delectus deleniti dolor harum illum perferendis quibusdam reiciendis voluptatum? Beatae consectetur cum enim fuga nisi odio similique! Ad aspernatur cumque doloribus dolorum eaque expedita in, nesciunt nulla sapiente!</span><span>Accusantium aliquid aut cumque cupiditate dolores eaque eveniet excepturi facilis harum illo libero natus nesciunt nulla quae quis quos repudiandae, voluptas voluptate! Ab commodi, doloremque dolorum facilis harum nobis porro!</span><span>A, ad asperiores distinctio doloribus itaque maxime neque nulla porro quibusdam quo sunt veritatis voluptates. Culpa cumque deserunt doloremque incidunt molestias quaerat quidem repellendus? Delectus, doloremque, voluptas? Fugit, recusandae suscipit.</span><span>At blanditiis commodi culpa cupiditate dignissimos, dolorum eos exercitationem facere hic id impedit itaque laborum magni minima numquam odit omnis possimus quidem recusandae repellendus sed sint sit totam ullam voluptatibus.</span></p>
            <p><span>Lorem ipsum dolor sit amet, consectetur adipisicing elit. A animi consequatur, cum deleniti dolores doloribus, enim esse hic ipsam numquam obcaecati officiis perspiciatis quidem repellendus saepe temporibus tenetur unde, veritatis.</span><span>Adipisci alias deserunt dolor, doloremque, dolores, laudantium maxime minus modi molestias nam nemo neque quis reprehenderit sequi sint? Adipisci aperiam deleniti doloribus ea eligendi ex libero perspiciatis quidem sunt unde?</span><span>Ad architecto at blanditiis culpa cupiditate deleniti eaque enim eum ex excepturi facilis fugiat illo illum incidunt iste iure laboriosam nisi odio porro quaerat quod reiciendis sapiente tenetur ullam, velit.</span><span>Eum fuga ipsa laborum quibusdam unde voluptate voluptatum. Ab dolorem expedita magni modi pariatur quam rem sunt. Ab, animi beatae debitis eos laboriosam minus mollitia provident quam quas quasi quis.</span><span>Deserunt eius fuga, laboriosam laborum rem velit. Doloribus ex explicabo iure necessitatibus obcaecati qui quia soluta. Commodi cumque cupiditate, debitis dolores esse fugit harum pariatur, perspiciatis quos ullam unde ut!</span><span>Accusamus amet asperiores assumenda aut corporis cum debitis deleniti dicta distinctio earum enim esse facere, facilis harum iste molestias nam non officiis omnis quasi quidem, rem reprehenderit sapiente sed velit!</span><span>A aspernatur, delectus deleniti dolor harum illum perferendis quibusdam reiciendis voluptatum? Beatae consectetur cum enim fuga nisi odio similique! Ad aspernatur cumque doloribus dolorum eaque expedita in, nesciunt nulla sapiente!</span><span>Accusantium aliquid aut cumque cupiditate dolores eaque eveniet excepturi facilis harum illo libero natus nesciunt nulla quae quis quos repudiandae, voluptas voluptate! Ab commodi, doloremque dolorum facilis harum nobis porro!</span><span>A, ad asperiores distinctio doloribus itaque maxime neque nulla porro quibusdam quo sunt veritatis voluptates. Culpa cumque deserunt doloremque incidunt molestias quaerat quidem repellendus? Delectus, doloremque, voluptas? Fugit, recusandae suscipit.</span><span>At blanditiis commodi culpa cupiditate dignissimos, dolorum eos exercitationem facere hic id impedit itaque laborum magni minima numquam odit omnis possimus quidem recusandae repellendus sed sint sit totam ullam voluptatibus.</span></p>
            <p><span>Lorem ipsum dolor sit amet, consectetur adipisicing elit. A animi consequatur, cum deleniti dolores doloribus, enim esse hic ipsam numquam obcaecati officiis perspiciatis quidem repellendus saepe temporibus tenetur unde, veritatis.</span><span>Adipisci alias deserunt dolor, doloremque, dolores, laudantium maxime minus modi molestias nam nemo neque quis reprehenderit sequi sint? Adipisci aperiam deleniti doloribus ea eligendi ex libero perspiciatis quidem sunt unde?</span><span>Ad architecto at blanditiis culpa cupiditate deleniti eaque enim eum ex excepturi facilis fugiat illo illum incidunt iste iure laboriosam nisi odio porro quaerat quod reiciendis sapiente tenetur ullam, velit.</span><span>Eum fuga ipsa laborum quibusdam unde voluptate voluptatum. Ab dolorem expedita magni modi pariatur quam rem sunt. Ab, animi beatae debitis eos laboriosam minus mollitia provident quam quas quasi quis.</span><span>Deserunt eius fuga, laboriosam laborum rem velit. Doloribus ex explicabo iure necessitatibus obcaecati qui quia soluta. Commodi cumque cupiditate, debitis dolores esse fugit harum pariatur, perspiciatis quos ullam unde ut!</span><span>Accusamus amet asperiores assumenda aut corporis cum debitis deleniti dicta distinctio earum enim esse facere, facilis harum iste molestias nam non officiis omnis quasi quidem, rem reprehenderit sapiente sed velit!</span><span>A aspernatur, delectus deleniti dolor harum illum perferendis quibusdam reiciendis voluptatum? Beatae consectetur cum enim fuga nisi odio similique! Ad aspernatur cumque doloribus dolorum eaque expedita in, nesciunt nulla sapiente!</span><span>Accusantium aliquid aut cumque cupiditate dolores eaque eveniet excepturi facilis harum illo libero natus nesciunt nulla quae quis quos repudiandae, voluptas voluptate! Ab commodi, doloremque dolorum facilis harum nobis porro!</span><span>A, ad asperiores distinctio doloribus itaque maxime neque nulla porro quibusdam quo sunt veritatis voluptates. Culpa cumque deserunt doloremque incidunt molestias quaerat quidem repellendus? Delectus, doloremque, voluptas? Fugit, recusandae suscipit.</span><span>At blanditiis commodi culpa cupiditate dignissimos, dolorum eos exercitationem facere hic id impedit itaque laborum magni minima numquam odit omnis possimus quidem recusandae repellendus sed sint sit totam ullam voluptatibus.</span></p>
            <p><span>Lorem ipsum dolor sit amet, consectetur adipisicing elit. A animi consequatur, cum deleniti dolores doloribus, enim esse hic ipsam numquam obcaecati officiis perspiciatis quidem repellendus saepe temporibus tenetur unde, veritatis.</span><span>Adipisci alias deserunt dolor, doloremque, dolores, laudantium maxime minus modi molestias nam nemo neque quis reprehenderit sequi sint? Adipisci aperiam deleniti doloribus ea eligendi ex libero perspiciatis quidem sunt unde?</span><span>Ad architecto at blanditiis culpa cupiditate deleniti eaque enim eum ex excepturi facilis fugiat illo illum incidunt iste iure laboriosam nisi odio porro quaerat quod reiciendis sapiente tenetur ullam, velit.</span><span>Eum fuga ipsa laborum quibusdam unde voluptate voluptatum. Ab dolorem expedita magni modi pariatur quam rem sunt. Ab, animi beatae debitis eos laboriosam minus mollitia provident quam quas quasi quis.</span><span>Deserunt eius fuga, laboriosam laborum rem velit. Doloribus ex explicabo iure necessitatibus obcaecati qui quia soluta. Commodi cumque cupiditate, debitis dolores esse fugit harum pariatur, perspiciatis quos ullam unde ut!</span><span>Accusamus amet asperiores assumenda aut corporis cum debitis deleniti dicta distinctio earum enim esse facere, facilis harum iste molestias nam non officiis omnis quasi quidem, rem reprehenderit sapiente sed velit!</span><span>A aspernatur, delectus deleniti dolor harum illum perferendis quibusdam reiciendis voluptatum? Beatae consectetur cum enim fuga nisi odio similique! Ad aspernatur cumque doloribus dolorum eaque expedita in, nesciunt nulla sapiente!</span><span>Accusantium aliquid aut cumque cupiditate dolores eaque eveniet excepturi facilis harum illo libero natus nesciunt nulla quae quis quos repudiandae, voluptas voluptate! Ab commodi, doloremque dolorum facilis harum nobis porro!</span><span>A, ad asperiores distinctio doloribus itaque maxime neque nulla porro quibusdam quo sunt veritatis voluptates. Culpa cumque deserunt doloremque incidunt molestias quaerat quidem repellendus? Delectus, doloremque, voluptas? Fugit, recusandae suscipit.</span><span>At blanditiis commodi culpa cupiditate dignissimos, dolorum eos exercitationem facere hic id impedit itaque laborum magni minima numquam odit omnis possimus quidem recusandae repellendus sed sint sit totam ullam voluptatibus.</span></p>
            <p><span>Lorem ipsum dolor sit amet, consectetur adipisicing elit. A animi consequatur, cum deleniti dolores doloribus, enim esse hic ipsam numquam obcaecati officiis perspiciatis quidem repellendus saepe temporibus tenetur unde, veritatis.</span><span>Adipisci alias deserunt dolor, doloremque, dolores, laudantium maxime minus modi molestias nam nemo neque quis reprehenderit sequi sint? Adipisci aperiam deleniti doloribus ea eligendi ex libero perspiciatis quidem sunt unde?</span><span>Ad architecto at blanditiis culpa cupiditate deleniti eaque enim eum ex excepturi facilis fugiat illo illum incidunt iste iure laboriosam nisi odio porro quaerat quod reiciendis sapiente tenetur ullam, velit.</span><span>Eum fuga ipsa laborum quibusdam unde voluptate voluptatum. Ab dolorem expedita magni modi pariatur quam rem sunt. Ab, animi beatae debitis eos laboriosam minus mollitia provident quam quas quasi quis.</span><span>Deserunt eius fuga, laboriosam laborum rem velit. Doloribus ex explicabo iure necessitatibus obcaecati qui quia soluta. Commodi cumque cupiditate, debitis dolores esse fugit harum pariatur, perspiciatis quos ullam unde ut!</span><span>Accusamus amet asperiores assumenda aut corporis cum debitis deleniti dicta distinctio earum enim esse facere, facilis harum iste molestias nam non officiis omnis quasi quidem, rem reprehenderit sapiente sed velit!</span><span>A aspernatur, delectus deleniti dolor harum illum perferendis quibusdam reiciendis voluptatum? Beatae consectetur cum enim fuga nisi odio similique! Ad aspernatur cumque doloribus dolorum eaque expedita in, nesciunt nulla sapiente!</span><span>Accusantium aliquid aut cumque cupiditate dolores eaque eveniet excepturi facilis harum illo libero natus nesciunt nulla quae quis quos repudiandae, voluptas voluptate! Ab commodi, doloremque dolorum facilis harum nobis porro!</span><span>A, ad asperiores distinctio doloribus itaque maxime neque nulla porro quibusdam quo sunt veritatis voluptates. Culpa cumque deserunt doloremque incidunt molestias quaerat quidem repellendus? Delectus, doloremque, voluptas? Fugit, recusandae suscipit.</span><span>At blanditiis commodi culpa cupiditate dignissimos, dolorum eos exercitationem facere hic id impedit itaque laborum magni minima numquam odit omnis possimus quidem recusandae repellendus sed sint sit totam ullam voluptatibus.</span></p>

          </div>
        </div>
        <div class="row checkb">
          <label class="pointer">
            <input type="checkbox" v-model="check1">
            <span class="checkbox"><i class="fa fa-check" aria-hidden="true"></i></span><span>Accept our privacy policy</span></label>
          <label class="pointer">
            <input type="checkbox" v-model="check2">
            <span class="checkbox"><i class="fa fa-check" aria-hidden="true"></i></span><span>Accept our privacy policy</span></label>
          <label class="pointer">
            <input type="checkbox" v-model="check3">
            <span class="checkbox"><i class="fa fa-check" aria-hidden="true"></i></span><span>Accept our privacy policy</span></label>
        </div>
        <div class="licensePage">
          <button v-on:click="next()">ACCEPT</button>
        </div>
      </div>
      <div class="licensePage sm">
        <button v-on:click="next()">ACCEPT</button>
      </div>
    </div>
  </div>

</template>

<script>
    export default {
        //name: 'app',
        data () {
            return {
                check1:false,
                check2:false,
                check3:false
            }
        },
        computed: {

        },
        methods: {
            next: function () {
                if(this.check1 && this.check2 && this.check3 && true){
                    this.$emit('onToUser')
                }
            }
        },
        created: function() {

        }
    }
</script>

<style>

</style>
